Fix test command invocation causing ERROR
Currently, running the test suite via the test command (pythonX.Y setup.py test) produces the following error:

```
ERROR: file not found: test
```

This change tweaks initialize_options to match the code described upstream [1].

[1] https://pytest.org/latest/goodpractises.html