limit filelock to highest compatible version
filelock 3.15.0 was just released and causes the following crash when used with the latest version of virtualenv

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

This change avoids depending on this new incompatible version of filelock.