fix: Correctly remove bk dir when re-signing macOS Python 2.x executable
Fixes #2271

> PermissionError: [Errno 1] Operation not permitted:
'/Users/alex/src/virtualenv/v27/bin/bk'

Requires #2270
Refs #2233